/*
 * optional_settings.hpp
 *
 *  Created on: 2019年4月19日
 *      Author: peter
 */

#ifndef INCLUDE_KERBAL_DATA_STRUCT_OPTIONAL_OPTIONAL_SETTINGS_HPP_
#define INCLUDE_KERBAL_DATA_STRUCT_OPTIONAL_OPTIONAL_SETTINGS_HPP_

#if !defined(KERBAL_OPTIONAL_ENABLE_SUPPORT_TO_STD_OPTIONAL)
#	if __cplusplus >= 201703L
#		define KERBAL_OPTIONAL_ENABLE_SUPPORT_TO_STD_OPTIONAL 1
#	else
#		define KERBAL_OPTIONAL_ENABLE_SUPPORT_TO_STD_OPTIONAL 0
#	endif
#endif


#if !defined(KERBAL_OPTIONAL_ENABLE_SUPPORT_TO_BOOST_OPTIONAL)
#	define KERBAL_OPTIONAL_ENABLE_SUPPORT_TO_BOOST_OPTIONAL 1
#endif


#endif /* INCLUDE_KERBAL_DATA_STRUCT_OPTIONAL_OPTIONAL_SETTINGS_HPP_ */
